#!/usr/bin/env bash

# Monitor arrangement for the bar's display panel.
#
# Hyprland places a newly connected monitor to the right of the existing
# layout. This script lets the user pick where an external display goes
# instead, persists the choice by EDID description (connector names such as
# DP-3 change with the port or dock) and applies it live.
#
# It is the only writer of ~/.config/blankweave/monitors.json, the source of
# truth, and of ~/.config/blankweave/monitors.lua, the Hyprland rules generated
# from it. The generated hyprland.lua loads the Lua file after the host's
# monitors.lua, so these rules win on every start.
#
# Usage:
#   monitor-layout.sh status                        JSON for the display panel
#   monitor-layout.sh set <connector> <position>    position: left|right|above|below|auto
#   monitor-layout.sh set-scale <connector> <scale> scale: auto or a supported numeric option
#   monitor-layout.sh apply                         regenerate and apply the rules

set -euo pipefail

config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
config_dir="$config_home/blankweave"
config_file="$config_dir/monitors.json"
rules_file="$config_dir/monitors.lua"

fail() {
    printf '%s\n' "$1" >&2
    exit 1
}

command -v jq >/dev/null 2>&1 || fail 'monitor-layout.sh requires jq'
command -v hyprctl >/dev/null 2>&1 || fail 'monitor-layout.sh requires hyprctl'

# Persisted entries as a JSON array; an unreadable file counts as empty.
persisted() {
    if [ -r "$config_file" ] && jq -e '.monitors | type == "array"' "$config_file" >/dev/null 2>&1; then
        jq -c '.monitors' "$config_file"
    else
        printf '[]\n'
    fi
}

live_monitors() {
    hyprctl monitors -j 2>/dev/null || fail 'Hyprland is not reachable'
}

# Hyprland's relative positions: the direction names the panel uses map to
# "auto-<direction>", which places the monitor against the layout so far.
hyprland_position() {
    case "$1" in
        left)  printf 'auto-left\n' ;;
        right) printf 'auto-right\n' ;;
        above) printf 'auto-up\n' ;;
        below) printf 'auto-down\n' ;;
        auto)  printf 'auto\n' ;;
        *) return 1 ;;
    esac
}

# A description is embedded in a Lua string literal and in a Hyprland
# selector, so keep it to plain printable ASCII without quote or backslash.
valid_description() {
    [[ $1 =~ ^[[:print:]]+$ ]] && [[ $1 != *'"'* ]] && [[ $1 != *\\* ]]
}

scale_options() {
    local monitor=$1

    # Hyprland requires a scale to produce whole logical pixels. Start with
    # useful desktop increments, discard invalid results for this mode, and
    # always retain the compositor's current value.
    jq -c '
        . as $monitor
        | def integral: ((. - round) | fabs) < 0.000001;
        def supported($scale):
            (($monitor.width / $scale) | integral)
            and (($monitor.height / $scale) | integral);
        (([1, 1.1, 1.2, 1.25, 1.3, 1.4, 1.5, 1.6, 1.75, 1.8, 2, 2.25, 2.5, 3]
            | map(select(supported(.)))) + [$monitor.scale]
            | map(select(type == "number" and . > 0))
            | unique)
    ' <<< "$monitor"
}

write_entries() {
    local entries=$1 staged

    mkdir -p "$config_dir"
    staged=$(mktemp "$config_dir/.monitors.json.XXXXXX")
    jq '{ monitors: . }' <<< "$entries" > "$staged"
    chmod 0644 "$staged"
    mv -f "$staged" "$config_file"
}

write_rules() {
    local entries staged

    entries=$(persisted)
    mkdir -p "$config_dir"
    staged=$(mktemp "$config_dir/.monitors.lua.XXXXXX")
    {
        printf -- '-- Generated by monitor-layout.sh from monitors.json. Do not edit;\n'
        printf -- '-- choose display position and scaling in the bar panel instead.\n'
        jq -r '
            def lua_scale:
                if . == "auto" then "\"auto\"" else tostring end;
            .[] | "hl.monitor({ output = \"desc:\(.description)\", mode = \"preferred\", position = \"\(.position)\", scale = \(.scale | lua_scale) })"
        ' <<< "$entries"
    } > "$staged"
    chmod 0644 "$staged"
    mv -f "$staged" "$rules_file"
}

apply_rules() {
    hyprctl eval "dofile(\"$rules_file\")" >/dev/null 2>&1 \
        || fail 'Hyprland rejected the generated monitor rules'
}

cmd_status() {
    local live entries

    live=$(live_monitors)
    entries=$(persisted)
    jq -c --argjson persisted "$entries" '
        def integral: ((. - round) | fabs) < 0.000001;
        def supported_scales($monitor):
            (([1, 1.1, 1.2, 1.25, 1.3, 1.4, 1.5, 1.6, 1.75, 1.8, 2, 2.25, 2.5, 3]
                | map(select(
                    (($monitor.width / .) | integral)
                    and (($monitor.height / .) | integral)
                ))) + [$monitor.scale]
                | map(select(type == "number" and . > 0))
                | unique);
        {
            monitors: [
                .[] | . as $monitor
                | ($persisted | map(select(.description == $monitor.description)) | first) as $entry
                | {
                    name: .name,
                    description: .description,
                    internal: (.name | test("^(eDP|LVDS|DSI)-")),
                    x: .x,
                    y: .y,
                    width: .width,
                    height: .height,
                    scale: (
                        if $entry != null and ($entry.scaleExplicit // false)
                        then ($entry.scale // $monitor.scale)
                        else $monitor.scale
                        end
                    ),
                    effectiveScale: .scale,
                    scaleOptions: supported_scales($monitor),
                    position: (
                        if $entry == null then "auto"
                        else ({
                            "auto-left": "left",
                            "auto-right": "right",
                            "auto-up": "above",
                            "auto-down": "below"
                        }[$entry.position] // "auto")
                        end
                    )
                }
            ]
        }' <<< "$live"
}

cmd_set() {
    local connector=$1 choice=$2
    local live monitor description scale position entries entry scale_explicit lua_scale

    position=$(hyprland_position "$choice") || fail "Unknown position: $choice"

    live=$(live_monitors)
    monitor=$(jq -c --arg name "$connector" '.[] | select(.name == $name)' <<< "$live")
    [ -n "$monitor" ] || fail "No connected monitor named $connector"

    description=$(jq -r '.description' <<< "$monitor")
    scale=$(jq -r '.scale' <<< "$monitor")
    valid_description "$description" || fail "Cannot persist a rule for this monitor's description"
    [[ $scale =~ ^[0-9]+(\.[0-9]+)?$ ]] || fail 'Hyprland reported no usable scale for this monitor'

    entries=$(persisted)
    entry=$(jq -c --arg description "$description" \
        'map(select(.description == $description)) | first // empty' <<< "$entries")
    scale_explicit=false
    if [ -n "$entry" ]; then
        scale=$(jq -r '.scale' <<< "$entry")
        scale_explicit=$(jq -r '.scaleExplicit // false' <<< "$entry")
    fi

    if [ "$choice" = auto ] && [ "$scale_explicit" != true ]; then
        entries=$(jq -c --arg description "$description" \
            'map(select(.description != $description))' <<< "$entries")
    else
        # A position-only rule freezes the live scale. A scale explicitly
        # chosen in the panel survives later position changes, including Auto.
        entries=$(jq -c --arg description "$description" --arg position "$position" \
            --arg scale "$scale" --argjson scaleExplicit "$scale_explicit" \
            'map(select(.description != $description)) + [{
                description: $description,
                position: $position,
                scale: (if $scale == "auto" then "auto" else ($scale | tonumber) end),
                scaleExplicit: $scaleExplicit
            }]' <<< "$entries")
    fi

    write_entries "$entries"

    write_rules
    apply_rules

    if [ "$choice" = auto ]; then
        # Dropping the rule does not move the monitor back; place it the
        # way Hyprland would have without one, for this session only.
        lua_scale=$scale
        [ "$scale" != auto ] || lua_scale='"auto"'
        hyprctl eval "hl.monitor({ output = \"desc:$description\", mode = \"preferred\", position = \"auto\", scale = $lua_scale })" \
            >/dev/null 2>&1 || true
    fi
}

cmd_set_scale() {
    local connector=$1 choice=$2
    local live monitor description position entries options normalized

    live=$(live_monitors)
    monitor=$(jq -c --arg name "$connector" '.[] | select(.name == $name)' <<< "$live")
    [ -n "$monitor" ] || fail "No connected monitor named $connector"

    description=$(jq -r '.description' <<< "$monitor")
    valid_description "$description" || fail "Cannot persist a rule for this monitor's description"

    if [ "$choice" = auto ]; then
        normalized=auto
    else
        [[ $choice =~ ^[0-9]+(\.[0-9]+)?$ ]] || fail "Unknown scale: $choice"
        options=$(scale_options "$monitor")
        jq -e --argjson wanted "$choice" 'index($wanted) != null' <<< "$options" \
            >/dev/null || fail "Scale $choice is not supported by $connector at its current resolution"
        normalized=$(jq -nr --argjson scale "$choice" '$scale')
    fi

    entries=$(persisted)
    position=$(jq -r --arg description "$description" '
        (map(select(.description == $description)) | first | .position) // "auto"
    ' <<< "$entries")
    entries=$(jq -c --arg description "$description" --arg position "$position" \
        --arg scale "$normalized" '
        map(select(.description != $description)) + [{
            description: $description,
            position: $position,
            scale: (if $scale == "auto" then "auto" else ($scale | tonumber) end),
            scaleExplicit: true
        }]
    ' <<< "$entries")

    write_entries "$entries"
    write_rules
    apply_rules
}

case "${1:-}" in
    status)
        cmd_status
        ;;
    set)
        [ $# -eq 3 ] || fail 'Usage: monitor-layout.sh set <connector> <left|right|above|below|auto>'
        cmd_set "$2" "$3"
        ;;
    set-scale)
        [ $# -eq 3 ] || fail 'Usage: monitor-layout.sh set-scale <connector> <auto|scale>'
        cmd_set_scale "$2" "$3"
        ;;
    apply)
        write_rules
        apply_rules
        ;;
    *)
        fail 'Usage: monitor-layout.sh {status|set <connector> <position>|set-scale <connector> <scale>|apply}'
        ;;
esac
