#!/usr/bin/env bash

# Monitor arrangement for the bar's display panel.
#
# Hyprland places a newly connected monitor to the right of the existing
# layout. This script lets the user pick where an external display goes
# instead, persists the choice by EDID description (connector names such as
# DP-3 change with the port or dock) and applies it live.
#
# It is the only writer of ~/.config/blankweave/monitors.json, the source of
# truth, and of ~/.config/blankweave/monitors.lua, the Hyprland rules generated
# from it. The generated hyprland.lua loads the Lua file after the host's
# monitors.lua, so these rules win on every start.
#
# Usage:
#   monitor-layout.sh status                        JSON for the display panel
#   monitor-layout.sh set <connector> <position>    position: left|right|above|below|auto
#   monitor-layout.sh apply                         regenerate and apply the rules

set -euo pipefail

config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
config_dir="$config_home/blankweave"
config_file="$config_dir/monitors.json"
rules_file="$config_dir/monitors.lua"

fail() {
    printf '%s\n' "$1" >&2
    exit 1
}

command -v jq >/dev/null 2>&1 || fail 'monitor-layout.sh requires jq'
command -v hyprctl >/dev/null 2>&1 || fail 'monitor-layout.sh requires hyprctl'

# Persisted entries as a JSON array; an unreadable file counts as empty.
persisted() {
    if [ -r "$config_file" ] && jq -e '.monitors | type == "array"' "$config_file" >/dev/null 2>&1; then
        jq -c '.monitors' "$config_file"
    else
        printf '[]\n'
    fi
}

live_monitors() {
    hyprctl monitors -j 2>/dev/null || fail 'Hyprland is not reachable'
}

# Hyprland's relative positions: the direction names the panel uses map to
# "auto-<direction>", which places the monitor against the layout so far.
hyprland_position() {
    case "$1" in
        left)  printf 'auto-left\n' ;;
        right) printf 'auto-right\n' ;;
        above) printf 'auto-up\n' ;;
        below) printf 'auto-down\n' ;;
        auto)  printf 'auto\n' ;;
        *) return 1 ;;
    esac
}

# A description is embedded in a Lua string literal and in a Hyprland
# selector, so keep it to plain printable ASCII without quote or backslash.
valid_description() {
    [[ $1 =~ ^[[:print:]]+$ ]] && [[ $1 != *'"'* ]] && [[ $1 != *\\* ]]
}

write_rules() {
    local entries staged

    entries=$(persisted)
    mkdir -p "$config_dir"
    staged=$(mktemp "$config_dir/.monitors.lua.XXXXXX")
    {
        printf -- '-- Generated by monitor-layout.sh from monitors.json. Do not edit;\n'
        printf -- '-- choose a position in the bar'"'"'s display panel instead.\n'
        jq -r '.[] | "hl.monitor({ output = \"desc:\(.description)\", mode = \"preferred\", position = \"\(.position)\", scale = \(.scale) })"' <<< "$entries"
    } > "$staged"
    chmod 0644 "$staged"
    mv -f "$staged" "$rules_file"
}

apply_rules() {
    hyprctl eval "dofile(\"$rules_file\")" >/dev/null 2>&1 \
        || fail 'Hyprland rejected the generated monitor rules'
}

cmd_status() {
    local live entries

    live=$(live_monitors)
    entries=$(persisted)
    jq -c --argjson persisted "$entries" '
        {
            monitors: [
                .[] | . as $monitor
                | ($persisted | map(select(.description == $monitor.description)) | first) as $entry
                | {
                    name: .name,
                    description: .description,
                    internal: (.name | test("^(eDP|LVDS|DSI)-")),
                    x: .x,
                    y: .y,
                    width: .width,
                    height: .height,
                    scale: .scale,
                    position: (
                        if $entry == null then "auto"
                        else ({
                            "auto-left": "left",
                            "auto-right": "right",
                            "auto-up": "above",
                            "auto-down": "below"
                        }[$entry.position] // "auto")
                        end
                    )
                }
            ]
        }' <<< "$live"
}

cmd_set() {
    local connector=$1 choice=$2
    local live monitor description scale position entries staged

    position=$(hyprland_position "$choice") || fail "Unknown position: $choice"

    live=$(live_monitors)
    monitor=$(jq -c --arg name "$connector" '.[] | select(.name == $name)' <<< "$live")
    [ -n "$monitor" ] || fail "No connected monitor named $connector"

    description=$(jq -r '.description' <<< "$monitor")
    scale=$(jq -r '.scale' <<< "$monitor")
    valid_description "$description" || fail "Cannot persist a rule for this monitor's description"
    [[ $scale =~ ^[0-9]+(\.[0-9]+)?$ ]] || fail 'Hyprland reported no usable scale for this monitor'

    entries=$(persisted)
    if [ "$choice" = auto ]; then
        entries=$(jq -c --arg description "$description" \
            'map(select(.description != $description))' <<< "$entries")
    else
        # The current scale is frozen into the rule so choosing a position
        # never changes the size of what is on screen.
        entries=$(jq -c --arg description "$description" --arg position "$position" --argjson scale "$scale" \
            'map(select(.description != $description)) + [{
                description: $description,
                position: $position,
                scale: $scale
            }]' <<< "$entries")
    fi

    mkdir -p "$config_dir"
    staged=$(mktemp "$config_dir/.monitors.json.XXXXXX")
    jq '{ monitors: . }' <<< "$entries" > "$staged"
    chmod 0644 "$staged"
    mv -f "$staged" "$config_file"

    write_rules
    apply_rules

    if [ "$choice" = auto ]; then
        # Dropping the rule does not move the monitor back; place it the
        # way Hyprland would have without one, for this session only.
        hyprctl eval "hl.monitor({ output = \"desc:$description\", mode = \"preferred\", position = \"auto\", scale = $scale })" \
            >/dev/null 2>&1 || true
    fi
}

case "${1:-}" in
    status)
        cmd_status
        ;;
    set)
        [ $# -eq 3 ] || fail 'Usage: monitor-layout.sh set <connector> <left|right|above|below|auto>'
        cmd_set "$2" "$3"
        ;;
    apply)
        write_rules
        apply_rules
        ;;
    *)
        fail 'Usage: monitor-layout.sh {status|set <connector> <position>|apply}'
        ;;
esac
