general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = ~/.local/share/blankweave/shell/brightness.sh dim 20
    on-resume = ~/.local/share/blankweave/shell/brightness.sh restore
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
